[package]
name = "curvecrypto"
version = "0.1.0"
edition = "2021"

[dependencies]
num = { version = "0.4.3", features = ["num-bigint"] }

[dev-dependencies]
k256 = { version = "0.13.3", features = ["ecdh"] }
rand = "0.8.5"
